# -*- coding: utf-8 -*-
"""CV Josemaría Moreno B.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BpoTrZDZfC9fFBI4T80rMdjt4wihFj9D
"""



"""# Ing. Mecatrónico
## Josemaría Moreno Balcázar       
![](https://raw.githubusercontent.com/jomorenoba/Clase-de-Herramientas-para-Ciencia-de-Datos/master/Foto%20ID%20Chema.png)

> **Edad:** 33 años
> **E-mail:** jmorenob@up.edu.mx
> **Celular:** 33 10 64 23 57

---
## Experiencia
### Actualmente
**Universidad Panamericana** ***Campus Guadalajara***
- Coordinador de Gestión Escolar en la Facultad de Ingeniería
---
## Herramientas Tecnológicas

- Paqueteria Office: Excel, Word, PowerPoint

## Lenguajes de Programación

1. Visual Basic
2. Python (en proceso)
---
## Intereses Personales
- Conocer y entender nuevos desarrollos tecnológicos
- Gusto por los Deportes como su seguimiento

|Deportes|Liga|
|--------|-------|
|Basket Ball|NBA|
|Football | España e Inglaterra|
"""